Repository aleortpag/decide-single-becquer, pull requests merged in 2023-12, with the labels that each got.

#25 Añade creacion de grupos de usuarios para crear censos automaticamente para una votacion
  decide/booth/tests.py
  decide/census/admin.py
  decide/census/models.py
  decide/voting/admin.py
  decide/voting/models.py
Labels: Preferencia Media, Código

#28 feat (Añade flake8 al proyecto y al workflow)
  .flake8
  .github/workflows/django.yml
  decide/authentication/admin.py
  decide/authentication/models.py
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/base/perms.py
  decide/base/views.py
  decide/booth/admin.py
  decide/booth/models.py
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/admin.py
  decide/census/migrations/0002_censusgroup.py
  decide/census/models.py
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/gateway/admin.py
  decide/gateway/models.py
  decide/gateway/tests.py
  decide/index/views.py
  decide/local_settings.gactions.py
  decide/mixnet/mixcrypt.py
  decide/mixnet/models.py
  decide/mixnet/tests.py
  decide/mixnet/views.py
  decide/postproc/admin.py
  decide/postproc/models.py
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/store/models.py
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
  decide/visualizer/admin.py
  decide/visualizer/models.py
  decide/visualizer/tests.py
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/management/commands/testvoting.py
  decide/voting/migrations/0005_questionoption_preference_voting_group_and_more.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/views.py
  docker/docker-settings.py
  loadtest/gen_census.py
  loadtest/locustfile.py
  requirements.txt
Labels: Preferencia Alta, Código, Configuración

#29 fix (Arregla algunos cambios detectados por flake8)
  .flake8
  decide/mixnet/mixcrypt.py
  loadtest/locustfile.py
Labels: bug, Preferencia Media, Código

#30 feat (Añade tests CRUD del modelo CensusGroup)
  decide/census/tests.py
Labels: Preferencia Media, Código

#40 Feature 014 - Vista votaciones disponible usuario
  decide/authentication/views.py
  decide/user/templates/user/availableVotings.html
  decide/user/urls.py
  decide/user/views.py
Labels: Preferencia Media, Código
